version: "3.9"
services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - '5672:5672'
        - '15672:15672'
      restart: always
  main-service:
    build:
      context: .
      dockerfile: Dockerfile-main
    ports:
      - "50051:50051"
    volumes:
      - ./:/app
    command:
      - reflex -r --start-service '\.go$' go run ./main-service/cmd
#  api-service:
#    build:
#      context: .
#      dockerfile: api-service/Dockerfile-main
#    volumes:
#      - ./:/app
#    ports:
#      - "50052:50052"
#  bank-service:
#    build:
#      context: .
#      dockerfile: bank-service/Dockerfile-main
#    volumes:
#      - ./:/app
#    ports:
#      - "50053:50053"
#    depends_on:
#      - rabbitmq
#      - mongodb