// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewEncryptorMock creates a new instance of EncryptorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncryptorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EncryptorMock {
	mock := &EncryptorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EncryptorMock is an autogenerated mock type for the Encryptor type
type EncryptorMock struct {
	mock.Mock
}

type EncryptorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EncryptorMock) EXPECT() *EncryptorMock_Expecter {
	return &EncryptorMock_Expecter{mock: &_m.Mock}
}

// Decrypt provides a mock function for the type EncryptorMock
func (_mock *EncryptorMock) Decrypt(encrypted string) (string, error) {
	ret := _mock.Called(encrypted)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(encrypted)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(encrypted)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(encrypted)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncryptorMock_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type EncryptorMock_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - encrypted string
func (_e *EncryptorMock_Expecter) Decrypt(encrypted interface{}) *EncryptorMock_Decrypt_Call {
	return &EncryptorMock_Decrypt_Call{Call: _e.mock.On("Decrypt", encrypted)}
}

func (_c *EncryptorMock_Decrypt_Call) Run(run func(encrypted string)) *EncryptorMock_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncryptorMock_Decrypt_Call) Return(s string, err error) *EncryptorMock_Decrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *EncryptorMock_Decrypt_Call) RunAndReturn(run func(encrypted string) (string, error)) *EncryptorMock_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type EncryptorMock
func (_mock *EncryptorMock) Encrypt(plaintext string) (string, error) {
	ret := _mock.Called(plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EncryptorMock_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type EncryptorMock_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - plaintext string
func (_e *EncryptorMock_Expecter) Encrypt(plaintext interface{}) *EncryptorMock_Encrypt_Call {
	return &EncryptorMock_Encrypt_Call{Call: _e.mock.On("Encrypt", plaintext)}
}

func (_c *EncryptorMock_Encrypt_Call) Run(run func(plaintext string)) *EncryptorMock_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EncryptorMock_Encrypt_Call) Return(s string, err error) *EncryptorMock_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *EncryptorMock_Encrypt_Call) RunAndReturn(run func(plaintext string) (string, error)) *EncryptorMock_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
