// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newProviderMock creates a new instance of providerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *providerMock {
	mock := &providerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// providerMock is an autogenerated mock type for the provider type
type providerMock struct {
	mock.Mock
}

type providerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *providerMock) EXPECT() *providerMock_Expecter {
	return &providerMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type providerMock
func (_mock *providerMock) Get(ctx context.Context, fid int, uid int64) (*entity.UserBankToken, error) {
	ret := _mock.Called(ctx, fid, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.UserBankToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) (*entity.UserBankToken, error)); ok {
		return returnFunc(ctx, fid, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) *entity.UserBankToken); ok {
		r0 = returnFunc(ctx, fid, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBankToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = returnFunc(ctx, fid, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// providerMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type providerMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
func (_e *providerMock_Expecter) Get(ctx interface{}, fid interface{}, uid interface{}) *providerMock_Get_Call {
	return &providerMock_Get_Call{Call: _e.mock.On("Get", ctx, fid, uid)}
}

func (_c *providerMock_Get_Call) Run(run func(ctx context.Context, fid int, uid int64)) *providerMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *providerMock_Get_Call) Return(userBankToken *entity.UserBankToken, err error) *providerMock_Get_Call {
	_c.Call.Return(userBankToken, err)
	return _c
}

func (_c *providerMock_Get_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64) (*entity.UserBankToken, error)) *providerMock_Get_Call {
	_c.Call.Return(run)
	return _c
}
