// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newSaverMock creates a new instance of saverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSaverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *saverMock {
	mock := &saverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// saverMock is an autogenerated mock type for the saver type
type saverMock struct {
	mock.Mock
}

type saverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *saverMock) EXPECT() *saverMock_Expecter {
	return &saverMock_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type saverMock
func (_mock *saverMock) Save(ctx context.Context, fid int, uid int64, token string) (*entity.UserBankToken, error) {
	ret := _mock.Called(ctx, fid, uid, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *entity.UserBankToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64, string) (*entity.UserBankToken, error)); ok {
		return returnFunc(ctx, fid, uid, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64, string) *entity.UserBankToken); ok {
		r0 = returnFunc(ctx, fid, uid, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBankToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int64, string) error); ok {
		r1 = returnFunc(ctx, fid, uid, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// saverMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type saverMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
//   - token string
func (_e *saverMock_Expecter) Save(ctx interface{}, fid interface{}, uid interface{}, token interface{}) *saverMock_Save_Call {
	return &saverMock_Save_Call{Call: _e.mock.On("Save", ctx, fid, uid, token)}
}

func (_c *saverMock_Save_Call) Run(run func(ctx context.Context, fid int, uid int64, token string)) *saverMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *saverMock_Save_Call) Return(userBankToken *entity.UserBankToken, err error) *saverMock_Save_Call {
	_c.Call.Return(userBankToken, err)
	return _c
}

func (_c *saverMock_Save_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64, token string) (*entity.UserBankToken, error)) *saverMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
