// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTokenIfaceMock creates a new instance of TokenIfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIfaceMock {
	mock := &TokenIfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIfaceMock is an autogenerated mock type for the TokenIface type
type TokenIfaceMock struct {
	mock.Mock
}

type TokenIfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIfaceMock) EXPECT() *TokenIfaceMock_Expecter {
	return &TokenIfaceMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type TokenIfaceMock
func (_mock *TokenIfaceMock) Delete(ctx context.Context, fid int, uid int64) error {
	ret := _mock.Called(ctx, fid, uid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = returnFunc(ctx, fid, uid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TokenIfaceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TokenIfaceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
func (_e *TokenIfaceMock_Expecter) Delete(ctx interface{}, fid interface{}, uid interface{}) *TokenIfaceMock_Delete_Call {
	return &TokenIfaceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, fid, uid)}
}

func (_c *TokenIfaceMock_Delete_Call) Run(run func(ctx context.Context, fid int, uid int64)) *TokenIfaceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIfaceMock_Delete_Call) Return(err error) *TokenIfaceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TokenIfaceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64) error) *TokenIfaceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type TokenIfaceMock
func (_mock *TokenIfaceMock) Get(ctx context.Context, fid int, uid int64) (*entity.UserBankToken, error) {
	ret := _mock.Called(ctx, fid, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.UserBankToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) (*entity.UserBankToken, error)); ok {
		return returnFunc(ctx, fid, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) *entity.UserBankToken); ok {
		r0 = returnFunc(ctx, fid, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBankToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int64) error); ok {
		r1 = returnFunc(ctx, fid, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIfaceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TokenIfaceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
func (_e *TokenIfaceMock_Expecter) Get(ctx interface{}, fid interface{}, uid interface{}) *TokenIfaceMock_Get_Call {
	return &TokenIfaceMock_Get_Call{Call: _e.mock.On("Get", ctx, fid, uid)}
}

func (_c *TokenIfaceMock_Get_Call) Run(run func(ctx context.Context, fid int, uid int64)) *TokenIfaceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenIfaceMock_Get_Call) Return(userBankToken *entity.UserBankToken, err error) *TokenIfaceMock_Get_Call {
	_c.Call.Return(userBankToken, err)
	return _c
}

func (_c *TokenIfaceMock_Get_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64) (*entity.UserBankToken, error)) *TokenIfaceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type TokenIfaceMock
func (_mock *TokenIfaceMock) Save(ctx context.Context, fid int, uid int64, token string) (*entity.UserBankToken, error) {
	ret := _mock.Called(ctx, fid, uid, token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *entity.UserBankToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64, string) (*entity.UserBankToken, error)); ok {
		return returnFunc(ctx, fid, uid, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64, string) *entity.UserBankToken); ok {
		r0 = returnFunc(ctx, fid, uid, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserBankToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int64, string) error); ok {
		r1 = returnFunc(ctx, fid, uid, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIfaceMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type TokenIfaceMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
//   - token string
func (_e *TokenIfaceMock_Expecter) Save(ctx interface{}, fid interface{}, uid interface{}, token interface{}) *TokenIfaceMock_Save_Call {
	return &TokenIfaceMock_Save_Call{Call: _e.mock.On("Save", ctx, fid, uid, token)}
}

func (_c *TokenIfaceMock_Save_Call) Run(run func(ctx context.Context, fid int, uid int64, token string)) *TokenIfaceMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenIfaceMock_Save_Call) Return(userBankToken *entity.UserBankToken, err error) *TokenIfaceMock_Save_Call {
	_c.Call.Return(userBankToken, err)
	return _c
}

func (_c *TokenIfaceMock_Save_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64, token string) (*entity.UserBankToken, error)) *TokenIfaceMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
