// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"
)

// newDeletorMock creates a new instance of deletorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDeletorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *deletorMock {
	mock := &deletorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// deletorMock is an autogenerated mock type for the deletor type
type deletorMock struct {
	mock.Mock
}

type deletorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *deletorMock) EXPECT() *deletorMock_Expecter {
	return &deletorMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type deletorMock
func (_mock *deletorMock) Delete(ctx context.Context, fn pgx.Tx, familyID int) error {
	ret := _mock.Called(ctx, fn, familyID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int) error); ok {
		r0 = returnFunc(ctx, fn, familyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// deletorMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type deletorMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - fn pgx.Tx
//   - familyID int
func (_e *deletorMock_Expecter) Delete(ctx interface{}, fn interface{}, familyID interface{}) *deletorMock_Delete_Call {
	return &deletorMock_Delete_Call{Call: _e.mock.On("Delete", ctx, fn, familyID)}
}

func (_c *deletorMock_Delete_Call) Run(run func(ctx context.Context, fn pgx.Tx, familyID int)) *deletorMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *deletorMock_Delete_Call) Return(err error) *deletorMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *deletorMock_Delete_Call) RunAndReturn(run func(ctx context.Context, fn pgx.Tx, familyID int) error) *deletorMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}
