// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"
	"time"

	"github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewFamilyIfaceMock creates a new instance of FamilyIfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFamilyIfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FamilyIfaceMock {
	mock := &FamilyIfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FamilyIfaceMock is an autogenerated mock type for the FamilyIface type
type FamilyIfaceMock struct {
	mock.Mock
}

type FamilyIfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FamilyIfaceMock) EXPECT() *FamilyIfaceMock_Expecter {
	return &FamilyIfaceMock_Expecter{mock: &_m.Mock}
}

// ClearInviteCodes provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) ClearInviteCodes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearInviteCodes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FamilyIfaceMock_ClearInviteCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearInviteCodes'
type FamilyIfaceMock_ClearInviteCodes_Call struct {
	*mock.Call
}

// ClearInviteCodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FamilyIfaceMock_Expecter) ClearInviteCodes(ctx interface{}) *FamilyIfaceMock_ClearInviteCodes_Call {
	return &FamilyIfaceMock_ClearInviteCodes_Call{Call: _e.mock.On("ClearInviteCodes", ctx)}
}

func (_c *FamilyIfaceMock_ClearInviteCodes_Call) Run(run func(ctx context.Context)) *FamilyIfaceMock_ClearInviteCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_ClearInviteCodes_Call) Return(err error) *FamilyIfaceMock_ClearInviteCodes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FamilyIfaceMock_ClearInviteCodes_Call) RunAndReturn(run func(ctx context.Context) error) *FamilyIfaceMock_ClearInviteCodes_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) Create(ctx context.Context, inp *entity.Family) (*entity.Family, error) {
	ret := _mock.Called(ctx, inp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Family) (*entity.Family, error)); ok {
		return returnFunc(ctx, inp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Family) *entity.Family); ok {
		r0 = returnFunc(ctx, inp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Family) error); ok {
		r1 = returnFunc(ctx, inp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FamilyIfaceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FamilyIfaceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - inp *entity.Family
func (_e *FamilyIfaceMock_Expecter) Create(ctx interface{}, inp interface{}) *FamilyIfaceMock_Create_Call {
	return &FamilyIfaceMock_Create_Call{Call: _e.mock.On("Create", ctx, inp)}
}

func (_c *FamilyIfaceMock_Create_Call) Run(run func(ctx context.Context, inp *entity.Family)) *FamilyIfaceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Family
		if args[1] != nil {
			arg1 = args[1].(*entity.Family)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_Create_Call) Return(family *entity.Family, err error) *FamilyIfaceMock_Create_Call {
	_c.Call.Return(family, err)
	return _c
}

func (_c *FamilyIfaceMock_Create_Call) RunAndReturn(run func(ctx context.Context, inp *entity.Family) (*entity.Family, error)) *FamilyIfaceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) Delete(ctx context.Context, fn pgx.Tx, fid int) error {
	ret := _mock.Called(ctx, fn, fid)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int) error); ok {
		r0 = returnFunc(ctx, fn, fid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FamilyIfaceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FamilyIfaceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - fn pgx.Tx
//   - fid int
func (_e *FamilyIfaceMock_Expecter) Delete(ctx interface{}, fn interface{}, fid interface{}) *FamilyIfaceMock_Delete_Call {
	return &FamilyIfaceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, fn, fid)}
}

func (_c *FamilyIfaceMock_Delete_Call) Run(run func(ctx context.Context, fn pgx.Tx, fid int)) *FamilyIfaceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_Delete_Call) Return(err error) *FamilyIfaceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FamilyIfaceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, fn pgx.Tx, fid int) error) *FamilyIfaceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) GetByCode(ctx context.Context, code string) (*entity.Family, time.Time, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Family
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Family, time.Time, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Family); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, code)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FamilyIfaceMock_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type FamilyIfaceMock_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *FamilyIfaceMock_Expecter) GetByCode(ctx interface{}, code interface{}) *FamilyIfaceMock_GetByCode_Call {
	return &FamilyIfaceMock_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *FamilyIfaceMock_GetByCode_Call) Run(run func(ctx context.Context, code string)) *FamilyIfaceMock_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_GetByCode_Call) Return(family *entity.Family, time1 time.Time, err error) *FamilyIfaceMock_GetByCode_Call {
	_c.Call.Return(family, time1, err)
	return _c
}

func (_c *FamilyIfaceMock_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*entity.Family, time.Time, error)) *FamilyIfaceMock_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) GetByID(ctx context.Context, id int) (*entity.Family, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.Family, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.Family); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FamilyIfaceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type FamilyIfaceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *FamilyIfaceMock_Expecter) GetByID(ctx interface{}, id interface{}) *FamilyIfaceMock_GetByID_Call {
	return &FamilyIfaceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *FamilyIfaceMock_GetByID_Call) Run(run func(ctx context.Context, id int)) *FamilyIfaceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_GetByID_Call) Return(family *entity.Family, err error) *FamilyIfaceMock_GetByID_Call {
	_c.Call.Return(family, err)
	return _c
}

func (_c *FamilyIfaceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*entity.Family, error)) *FamilyIfaceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamiliesByUserID provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) GetFamiliesByUserID(ctx context.Context, uid int64) ([]entity.Family, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetFamiliesByUserID")
	}

	var r0 []entity.Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Family, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []entity.Family); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FamilyIfaceMock_GetFamiliesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamiliesByUserID'
type FamilyIfaceMock_GetFamiliesByUserID_Call struct {
	*mock.Call
}

// GetFamiliesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid int64
func (_e *FamilyIfaceMock_Expecter) GetFamiliesByUserID(ctx interface{}, uid interface{}) *FamilyIfaceMock_GetFamiliesByUserID_Call {
	return &FamilyIfaceMock_GetFamiliesByUserID_Call{Call: _e.mock.On("GetFamiliesByUserID", ctx, uid)}
}

func (_c *FamilyIfaceMock_GetFamiliesByUserID_Call) Run(run func(ctx context.Context, uid int64)) *FamilyIfaceMock_GetFamiliesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_GetFamiliesByUserID_Call) Return(familys []entity.Family, err error) *FamilyIfaceMock_GetFamiliesByUserID_Call {
	_c.Call.Return(familys, err)
	return _c
}

func (_c *FamilyIfaceMock_GetFamiliesByUserID_Call) RunAndReturn(run func(ctx context.Context, uid int64) ([]entity.Family, error)) *FamilyIfaceMock_GetFamiliesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInviteCode provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) GetInviteCode(ctx context.Context, fid int) (string, time.Time, error) {
	ret := _mock.Called(ctx, fid)

	if len(ret) == 0 {
		panic("no return value specified for GetInviteCode")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, time.Time, error)); ok {
		return returnFunc(ctx, fid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, fid)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) time.Time); ok {
		r1 = returnFunc(ctx, fid)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, fid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FamilyIfaceMock_GetInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInviteCode'
type FamilyIfaceMock_GetInviteCode_Call struct {
	*mock.Call
}

// GetInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
func (_e *FamilyIfaceMock_Expecter) GetInviteCode(ctx interface{}, fid interface{}) *FamilyIfaceMock_GetInviteCode_Call {
	return &FamilyIfaceMock_GetInviteCode_Call{Call: _e.mock.On("GetInviteCode", ctx, fid)}
}

func (_c *FamilyIfaceMock_GetInviteCode_Call) Run(run func(ctx context.Context, fid int)) *FamilyIfaceMock_GetInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_GetInviteCode_Call) Return(s string, time1 time.Time, err error) *FamilyIfaceMock_GetInviteCode_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *FamilyIfaceMock_GetInviteCode_Call) RunAndReturn(run func(ctx context.Context, fid int) (string, time.Time, error)) *FamilyIfaceMock_GetInviteCode_Call {
	_c.Call.Return(run)
	return _c
}

// SaveInviteCode provides a mock function for the type FamilyIfaceMock
func (_mock *FamilyIfaceMock) SaveInviteCode(ctx context.Context, uid int64, fid int, code string) (time.Time, error) {
	ret := _mock.Called(ctx, uid, fid, code)

	if len(ret) == 0 {
		panic("no return value specified for SaveInviteCode")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string) (time.Time, error)); ok {
		return returnFunc(ctx, uid, fid, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string) time.Time); ok {
		r0 = returnFunc(ctx, uid, fid, code)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, string) error); ok {
		r1 = returnFunc(ctx, uid, fid, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FamilyIfaceMock_SaveInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveInviteCode'
type FamilyIfaceMock_SaveInviteCode_Call struct {
	*mock.Call
}

// SaveInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - uid int64
//   - fid int
//   - code string
func (_e *FamilyIfaceMock_Expecter) SaveInviteCode(ctx interface{}, uid interface{}, fid interface{}, code interface{}) *FamilyIfaceMock_SaveInviteCode_Call {
	return &FamilyIfaceMock_SaveInviteCode_Call{Call: _e.mock.On("SaveInviteCode", ctx, uid, fid, code)}
}

func (_c *FamilyIfaceMock_SaveInviteCode_Call) Run(run func(ctx context.Context, uid int64, fid int, code string)) *FamilyIfaceMock_SaveInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *FamilyIfaceMock_SaveInviteCode_Call) Return(time1 time.Time, err error) *FamilyIfaceMock_SaveInviteCode_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *FamilyIfaceMock_SaveInviteCode_Call) RunAndReturn(run func(ctx context.Context, uid int64, fid int, code string) (time.Time, error)) *FamilyIfaceMock_SaveInviteCode_Call {
	_c.Call.Return(run)
	return _c
}
