// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newInviteCodeSaverMock creates a new instance of inviteCodeSaverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInviteCodeSaverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *inviteCodeSaverMock {
	mock := &inviteCodeSaverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// inviteCodeSaverMock is an autogenerated mock type for the inviteCodeSaver type
type inviteCodeSaverMock struct {
	mock.Mock
}

type inviteCodeSaverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *inviteCodeSaverMock) EXPECT() *inviteCodeSaverMock_Expecter {
	return &inviteCodeSaverMock_Expecter{mock: &_m.Mock}
}

// SaveInviteCode provides a mock function for the type inviteCodeSaverMock
func (_mock *inviteCodeSaverMock) SaveInviteCode(ctx context.Context, uid int64, fid int, code string) (time.Time, error) {
	ret := _mock.Called(ctx, uid, fid, code)

	if len(ret) == 0 {
		panic("no return value specified for SaveInviteCode")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string) (time.Time, error)); ok {
		return returnFunc(ctx, uid, fid, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, string) time.Time); ok {
		r0 = returnFunc(ctx, uid, fid, code)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, string) error); ok {
		r1 = returnFunc(ctx, uid, fid, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// inviteCodeSaverMock_SaveInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveInviteCode'
type inviteCodeSaverMock_SaveInviteCode_Call struct {
	*mock.Call
}

// SaveInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - uid int64
//   - fid int
//   - code string
func (_e *inviteCodeSaverMock_Expecter) SaveInviteCode(ctx interface{}, uid interface{}, fid interface{}, code interface{}) *inviteCodeSaverMock_SaveInviteCode_Call {
	return &inviteCodeSaverMock_SaveInviteCode_Call{Call: _e.mock.On("SaveInviteCode", ctx, uid, fid, code)}
}

func (_c *inviteCodeSaverMock_SaveInviteCode_Call) Run(run func(ctx context.Context, uid int64, fid int, code string)) *inviteCodeSaverMock_SaveInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *inviteCodeSaverMock_SaveInviteCode_Call) Return(time1 time.Time, err error) *inviteCodeSaverMock_SaveInviteCode_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *inviteCodeSaverMock_SaveInviteCode_Call) RunAndReturn(run func(ctx context.Context, uid int64, fid int, code string) (time.Time, error)) *inviteCodeSaverMock_SaveInviteCode_Call {
	_c.Call.Return(run)
	return _c
}
