// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newInviteCodeCleanerMock creates a new instance of inviteCodeCleanerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInviteCodeCleanerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *inviteCodeCleanerMock {
	mock := &inviteCodeCleanerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// inviteCodeCleanerMock is an autogenerated mock type for the inviteCodeCleaner type
type inviteCodeCleanerMock struct {
	mock.Mock
}

type inviteCodeCleanerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *inviteCodeCleanerMock) EXPECT() *inviteCodeCleanerMock_Expecter {
	return &inviteCodeCleanerMock_Expecter{mock: &_m.Mock}
}

// ClearInviteCodes provides a mock function for the type inviteCodeCleanerMock
func (_mock *inviteCodeCleanerMock) ClearInviteCodes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearInviteCodes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// inviteCodeCleanerMock_ClearInviteCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearInviteCodes'
type inviteCodeCleanerMock_ClearInviteCodes_Call struct {
	*mock.Call
}

// ClearInviteCodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *inviteCodeCleanerMock_Expecter) ClearInviteCodes(ctx interface{}) *inviteCodeCleanerMock_ClearInviteCodes_Call {
	return &inviteCodeCleanerMock_ClearInviteCodes_Call{Call: _e.mock.On("ClearInviteCodes", ctx)}
}

func (_c *inviteCodeCleanerMock_ClearInviteCodes_Call) Run(run func(ctx context.Context)) *inviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *inviteCodeCleanerMock_ClearInviteCodes_Call) Return(err error) *inviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *inviteCodeCleanerMock_ClearInviteCodes_Call) RunAndReturn(run func(ctx context.Context) error) *inviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Return(run)
	return _c
}
