// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newInviteCodeProviderMock creates a new instance of inviteCodeProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newInviteCodeProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *inviteCodeProviderMock {
	mock := &inviteCodeProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// inviteCodeProviderMock is an autogenerated mock type for the inviteCodeProvider type
type inviteCodeProviderMock struct {
	mock.Mock
}

type inviteCodeProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *inviteCodeProviderMock) EXPECT() *inviteCodeProviderMock_Expecter {
	return &inviteCodeProviderMock_Expecter{mock: &_m.Mock}
}

// GetInviteCode provides a mock function for the type inviteCodeProviderMock
func (_mock *inviteCodeProviderMock) GetInviteCode(ctx context.Context, fid int) (string, time.Time, error) {
	ret := _mock.Called(ctx, fid)

	if len(ret) == 0 {
		panic("no return value specified for GetInviteCode")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (string, time.Time, error)); ok {
		return returnFunc(ctx, fid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) string); ok {
		r0 = returnFunc(ctx, fid)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) time.Time); ok {
		r1 = returnFunc(ctx, fid)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int) error); ok {
		r2 = returnFunc(ctx, fid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// inviteCodeProviderMock_GetInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInviteCode'
type inviteCodeProviderMock_GetInviteCode_Call struct {
	*mock.Call
}

// GetInviteCode is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
func (_e *inviteCodeProviderMock_Expecter) GetInviteCode(ctx interface{}, fid interface{}) *inviteCodeProviderMock_GetInviteCode_Call {
	return &inviteCodeProviderMock_GetInviteCode_Call{Call: _e.mock.On("GetInviteCode", ctx, fid)}
}

func (_c *inviteCodeProviderMock_GetInviteCode_Call) Run(run func(ctx context.Context, fid int)) *inviteCodeProviderMock_GetInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *inviteCodeProviderMock_GetInviteCode_Call) Return(s string, time1 time.Time, err error) *inviteCodeProviderMock_GetInviteCode_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *inviteCodeProviderMock_GetInviteCode_Call) RunAndReturn(run func(ctx context.Context, fid int) (string, time.Time, error)) *inviteCodeProviderMock_GetInviteCode_Call {
	_c.Call.Return(run)
	return _c
}
