// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// newProviderMock creates a new instance of providerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *providerMock {
	mock := &providerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// providerMock is an autogenerated mock type for the provider type
type providerMock struct {
	mock.Mock
}

type providerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *providerMock) EXPECT() *providerMock_Expecter {
	return &providerMock_Expecter{mock: &_m.Mock}
}

// GetByCode provides a mock function for the type providerMock
func (_mock *providerMock) GetByCode(ctx context.Context, code string) (*entity.Family, time.Time, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *entity.Family
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.Family, time.Time, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.Family); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, code)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// providerMock_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type providerMock_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *providerMock_Expecter) GetByCode(ctx interface{}, code interface{}) *providerMock_GetByCode_Call {
	return &providerMock_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *providerMock_GetByCode_Call) Run(run func(ctx context.Context, code string)) *providerMock_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *providerMock_GetByCode_Call) Return(family *entity.Family, time1 time.Time, err error) *providerMock_GetByCode_Call {
	_c.Call.Return(family, time1, err)
	return _c
}

func (_c *providerMock_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*entity.Family, time.Time, error)) *providerMock_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type providerMock
func (_mock *providerMock) GetByID(ctx context.Context, id int) (*entity.Family, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*entity.Family, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *entity.Family); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// providerMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type providerMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *providerMock_Expecter) GetByID(ctx interface{}, id interface{}) *providerMock_GetByID_Call {
	return &providerMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *providerMock_GetByID_Call) Run(run func(ctx context.Context, id int)) *providerMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *providerMock_GetByID_Call) Return(family *entity.Family, err error) *providerMock_GetByID_Call {
	_c.Call.Return(family, err)
	return _c
}

func (_c *providerMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int) (*entity.Family, error)) *providerMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFamiliesByUserID provides a mock function for the type providerMock
func (_mock *providerMock) GetFamiliesByUserID(ctx context.Context, uid int64) ([]entity.Family, error) {
	ret := _mock.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for GetFamiliesByUserID")
	}

	var r0 []entity.Family
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]entity.Family, error)); ok {
		return returnFunc(ctx, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []entity.Family); ok {
		r0 = returnFunc(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Family)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// providerMock_GetFamiliesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFamiliesByUserID'
type providerMock_GetFamiliesByUserID_Call struct {
	*mock.Call
}

// GetFamiliesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid int64
func (_e *providerMock_Expecter) GetFamiliesByUserID(ctx interface{}, uid interface{}) *providerMock_GetFamiliesByUserID_Call {
	return &providerMock_GetFamiliesByUserID_Call{Call: _e.mock.On("GetFamiliesByUserID", ctx, uid)}
}

func (_c *providerMock_GetFamiliesByUserID_Call) Run(run func(ctx context.Context, uid int64)) *providerMock_GetFamiliesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *providerMock_GetFamiliesByUserID_Call) Return(familys []entity.Family, err error) *providerMock_GetFamiliesByUserID_Call {
	_c.Call.Return(familys, err)
	return _c
}

func (_c *providerMock_GetFamiliesByUserID_Call) RunAndReturn(run func(ctx context.Context, uid int64) ([]entity.Family, error)) *providerMock_GetFamiliesByUserID_Call {
	_c.Call.Return(run)
	return _c
}
