env: prod
bot:
  bot_token: TELEGRAM_BOT_TOKEN
  long_poller: 10
mono:
  mono_api_url: https://api.monobank.ua/personal/client-info
db:
  db_user: admin
  db_pass: admin
  db_host: localhost
  db_port: 5432
  db_name: dbname