// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"
)

// newDeletorMock creates a new instance of deletorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newDeletorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *deletorMock {
	mock := &deletorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// deletorMock is an autogenerated mock type for the deletor type
type deletorMock struct {
	mock.Mock
}

type deletorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *deletorMock) EXPECT() *deletorMock_Expecter {
	return &deletorMock_Expecter{mock: &_m.Mock}
}

// DeleteFromFamily provides a mock function for the type deletorMock
func (_mock *deletorMock) DeleteFromFamily(context1 context.Context, tx pgx.Tx, n int, n1 int64) error {
	ret := _mock.Called(context1, tx, n, n1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int64) error); ok {
		r0 = returnFunc(context1, tx, n, n1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// deletorMock_DeleteFromFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromFamily'
type deletorMock_DeleteFromFamily_Call struct {
	*mock.Call
}

// DeleteFromFamily is a helper method to define mock.On call
//   - context1 context.Context
//   - tx pgx.Tx
//   - n int
//   - n1 int64
func (_e *deletorMock_Expecter) DeleteFromFamily(context1 interface{}, tx interface{}, n interface{}, n1 interface{}) *deletorMock_DeleteFromFamily_Call {
	return &deletorMock_DeleteFromFamily_Call{Call: _e.mock.On("DeleteFromFamily", context1, tx, n, n1)}
}

func (_c *deletorMock_DeleteFromFamily_Call) Run(run func(context1 context.Context, tx pgx.Tx, n int, n1 int64)) *deletorMock_DeleteFromFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *deletorMock_DeleteFromFamily_Call) Return(err error) *deletorMock_DeleteFromFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *deletorMock_DeleteFromFamily_Call) RunAndReturn(run func(context1 context.Context, tx pgx.Tx, n int, n1 int64) error) *deletorMock_DeleteFromFamily_Call {
	_c.Call.Return(run)
	return _c
}
