// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newProviderMock creates a new instance of providerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *providerMock {
	mock := &providerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// providerMock is an autogenerated mock type for the provider type
type providerMock struct {
	mock.Mock
}

type providerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *providerMock) EXPECT() *providerMock_Expecter {
	return &providerMock_Expecter{mock: &_m.Mock}
}

// GetAllUsersInFamily provides a mock function for the type providerMock
func (_mock *providerMock) GetAllUsersInFamily(ctx context.Context, fid int) ([]entity.User, error) {
	ret := _mock.Called(ctx, fid)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersInFamily")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.User, error)); ok {
		return returnFunc(ctx, fid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.User); ok {
		r0 = returnFunc(ctx, fid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, fid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// providerMock_GetAllUsersInFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersInFamily'
type providerMock_GetAllUsersInFamily_Call struct {
	*mock.Call
}

// GetAllUsersInFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
func (_e *providerMock_Expecter) GetAllUsersInFamily(ctx interface{}, fid interface{}) *providerMock_GetAllUsersInFamily_Call {
	return &providerMock_GetAllUsersInFamily_Call{Call: _e.mock.On("GetAllUsersInFamily", ctx, fid)}
}

func (_c *providerMock_GetAllUsersInFamily_Call) Run(run func(ctx context.Context, fid int)) *providerMock_GetAllUsersInFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *providerMock_GetAllUsersInFamily_Call) Return(users []entity.User, err error) *providerMock_GetAllUsersInFamily_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *providerMock_GetAllUsersInFamily_Call) RunAndReturn(run func(ctx context.Context, fid int) ([]entity.User, error)) *providerMock_GetAllUsersInFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type providerMock
func (_mock *providerMock) GetByID(ctx context.Context, fid int64) (*entity.User, error) {
	ret := _mock.Called(ctx, fid)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.User, error)); ok {
		return returnFunc(ctx, fid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = returnFunc(ctx, fid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, fid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// providerMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type providerMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int64
func (_e *providerMock_Expecter) GetByID(ctx interface{}, fid interface{}) *providerMock_GetByID_Call {
	return &providerMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, fid)}
}

func (_c *providerMock_GetByID_Call) Run(run func(ctx context.Context, fid int64)) *providerMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *providerMock_GetByID_Call) Return(user *entity.User, err error) *providerMock_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *providerMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, fid int64) (*entity.User, error)) *providerMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
