// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// newSaverMock creates a new instance of saverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSaverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *saverMock {
	mock := &saverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// saverMock is an autogenerated mock type for the saver type
type saverMock struct {
	mock.Mock
}

type saverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *saverMock) EXPECT() *saverMock_Expecter {
	return &saverMock_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type saverMock
func (_mock *saverMock) Save(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// saverMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type saverMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *saverMock_Expecter) Save(ctx interface{}, user interface{}) *saverMock_Save_Call {
	return &saverMock_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *saverMock_Save_Call) Run(run func(ctx context.Context, user *entity.User)) *saverMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *saverMock_Save_Call) Return(user1 *entity.User, err error) *saverMock_Save_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *saverMock_Save_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *saverMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToFamily provides a mock function for the type saverMock
func (_mock *saverMock) SaveToFamily(ctx context.Context, familyID int, userID int64) error {
	ret := _mock.Called(ctx, familyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveToFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = returnFunc(ctx, familyID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// saverMock_SaveToFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToFamily'
type saverMock_SaveToFamily_Call struct {
	*mock.Call
}

// SaveToFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int
//   - userID int64
func (_e *saverMock_Expecter) SaveToFamily(ctx interface{}, familyID interface{}, userID interface{}) *saverMock_SaveToFamily_Call {
	return &saverMock_SaveToFamily_Call{Call: _e.mock.On("SaveToFamily", ctx, familyID, userID)}
}

func (_c *saverMock_SaveToFamily_Call) Run(run func(ctx context.Context, familyID int, userID int64)) *saverMock_SaveToFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *saverMock_SaveToFamily_Call) Return(err error) *saverMock_SaveToFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *saverMock_SaveToFamily_Call) RunAndReturn(run func(ctx context.Context, familyID int, userID int64) error) *saverMock_SaveToFamily_Call {
	_c.Call.Return(run)
	return _c
}
