// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTokenProviderMock creates a new instance of TokenProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenProviderMock {
	mock := &TokenProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenProviderMock is an autogenerated mock type for the TokenProvider type
type TokenProviderMock struct {
	mock.Mock
}

type TokenProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenProviderMock) EXPECT() *TokenProviderMock_Expecter {
	return &TokenProviderMock_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type TokenProviderMock
func (_mock *TokenProviderMock) Get(ctx context.Context, fid int, uid int64) (bool, *entity.UserBankToken, error) {
	ret := _mock.Called(ctx, fid, uid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 *entity.UserBankToken
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) (bool, *entity.UserBankToken, error)); ok {
		return returnFunc(ctx, fid, uid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) bool); ok {
		r0 = returnFunc(ctx, fid, uid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int64) *entity.UserBankToken); ok {
		r1 = returnFunc(ctx, fid, uid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.UserBankToken)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int64) error); ok {
		r2 = returnFunc(ctx, fid, uid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenProviderMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type TokenProviderMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fid int
//   - uid int64
func (_e *TokenProviderMock_Expecter) Get(ctx interface{}, fid interface{}, uid interface{}) *TokenProviderMock_Get_Call {
	return &TokenProviderMock_Get_Call{Call: _e.mock.On("Get", ctx, fid, uid)}
}

func (_c *TokenProviderMock_Get_Call) Run(run func(ctx context.Context, fid int, uid int64)) *TokenProviderMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TokenProviderMock_Get_Call) Return(b bool, userBankToken *entity.UserBankToken, err error) *TokenProviderMock_Get_Call {
	_c.Call.Return(b, userBankToken, err)
	return _c
}

func (_c *TokenProviderMock_Get_Call) RunAndReturn(run func(ctx context.Context, fid int, uid int64) (bool, *entity.UserBankToken, error)) *TokenProviderMock_Get_Call {
	_c.Call.Return(run)
	return _c
}
