// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"cashly/internal/entity"
	"context"

	"github.com/jackc/pgx/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewUserIfaceMock creates a new instance of UserIfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserIfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIfaceMock {
	mock := &UserIfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserIfaceMock is an autogenerated mock type for the UserIface type
type UserIfaceMock struct {
	mock.Mock
}

type UserIfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserIfaceMock) EXPECT() *UserIfaceMock_Expecter {
	return &UserIfaceMock_Expecter{mock: &_m.Mock}
}

// DeleteFromFamily provides a mock function for the type UserIfaceMock
func (_mock *UserIfaceMock) DeleteFromFamily(ctx context.Context, tx pgx.Tx, familyID int, userID int64) error {
	ret := _mock.Called(ctx, tx, familyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFromFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.Tx, int, int64) error); ok {
		r0 = returnFunc(ctx, tx, familyID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserIfaceMock_DeleteFromFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromFamily'
type UserIfaceMock_DeleteFromFamily_Call struct {
	*mock.Call
}

// DeleteFromFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - tx pgx.Tx
//   - familyID int
//   - userID int64
func (_e *UserIfaceMock_Expecter) DeleteFromFamily(ctx interface{}, tx interface{}, familyID interface{}, userID interface{}) *UserIfaceMock_DeleteFromFamily_Call {
	return &UserIfaceMock_DeleteFromFamily_Call{Call: _e.mock.On("DeleteFromFamily", ctx, tx, familyID, userID)}
}

func (_c *UserIfaceMock_DeleteFromFamily_Call) Run(run func(ctx context.Context, tx pgx.Tx, familyID int, userID int64)) *UserIfaceMock_DeleteFromFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.Tx
		if args[1] != nil {
			arg1 = args[1].(pgx.Tx)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserIfaceMock_DeleteFromFamily_Call) Return(err error) *UserIfaceMock_DeleteFromFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserIfaceMock_DeleteFromFamily_Call) RunAndReturn(run func(ctx context.Context, tx pgx.Tx, familyID int, userID int64) error) *UserIfaceMock_DeleteFromFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllUsersInFamily provides a mock function for the type UserIfaceMock
func (_mock *UserIfaceMock) GetAllUsersInFamily(ctx context.Context, familyID int) ([]entity.User, error) {
	ret := _mock.Called(ctx, familyID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersInFamily")
	}

	var r0 []entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]entity.User, error)); ok {
		return returnFunc(ctx, familyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []entity.User); ok {
		r0 = returnFunc(ctx, familyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, familyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserIfaceMock_GetAllUsersInFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersInFamily'
type UserIfaceMock_GetAllUsersInFamily_Call struct {
	*mock.Call
}

// GetAllUsersInFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int
func (_e *UserIfaceMock_Expecter) GetAllUsersInFamily(ctx interface{}, familyID interface{}) *UserIfaceMock_GetAllUsersInFamily_Call {
	return &UserIfaceMock_GetAllUsersInFamily_Call{Call: _e.mock.On("GetAllUsersInFamily", ctx, familyID)}
}

func (_c *UserIfaceMock_GetAllUsersInFamily_Call) Run(run func(ctx context.Context, familyID int)) *UserIfaceMock_GetAllUsersInFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserIfaceMock_GetAllUsersInFamily_Call) Return(users []entity.User, err error) *UserIfaceMock_GetAllUsersInFamily_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *UserIfaceMock_GetAllUsersInFamily_Call) RunAndReturn(run func(ctx context.Context, familyID int) ([]entity.User, error)) *UserIfaceMock_GetAllUsersInFamily_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type UserIfaceMock
func (_mock *UserIfaceMock) GetByID(ctx context.Context, id int64) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserIfaceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserIfaceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserIfaceMock_Expecter) GetByID(ctx interface{}, id interface{}) *UserIfaceMock_GetByID_Call {
	return &UserIfaceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserIfaceMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *UserIfaceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserIfaceMock_GetByID_Call) Return(user *entity.User, err error) *UserIfaceMock_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserIfaceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*entity.User, error)) *UserIfaceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type UserIfaceMock
func (_mock *UserIfaceMock) Save(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserIfaceMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type UserIfaceMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *UserIfaceMock_Expecter) Save(ctx interface{}, user interface{}) *UserIfaceMock_Save_Call {
	return &UserIfaceMock_Save_Call{Call: _e.mock.On("Save", ctx, user)}
}

func (_c *UserIfaceMock_Save_Call) Run(run func(ctx context.Context, user *entity.User)) *UserIfaceMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserIfaceMock_Save_Call) Return(user1 *entity.User, err error) *UserIfaceMock_Save_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserIfaceMock_Save_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *UserIfaceMock_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveToFamily provides a mock function for the type UserIfaceMock
func (_mock *UserIfaceMock) SaveToFamily(ctx context.Context, familyID int, userID int64) error {
	ret := _mock.Called(ctx, familyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveToFamily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int64) error); ok {
		r0 = returnFunc(ctx, familyID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserIfaceMock_SaveToFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveToFamily'
type UserIfaceMock_SaveToFamily_Call struct {
	*mock.Call
}

// SaveToFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - familyID int
//   - userID int64
func (_e *UserIfaceMock_Expecter) SaveToFamily(ctx interface{}, familyID interface{}, userID interface{}) *UserIfaceMock_SaveToFamily_Call {
	return &UserIfaceMock_SaveToFamily_Call{Call: _e.mock.On("SaveToFamily", ctx, familyID, userID)}
}

func (_c *UserIfaceMock_SaveToFamily_Call) Run(run func(ctx context.Context, familyID int, userID int64)) *UserIfaceMock_SaveToFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserIfaceMock_SaveToFamily_Call) Return(err error) *UserIfaceMock_SaveToFamily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserIfaceMock_SaveToFamily_Call) RunAndReturn(run func(ctx context.Context, familyID int, userID int64) error) *UserIfaceMock_SaveToFamily_Call {
	_c.Call.Return(run)
	return _c
}
