// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewFamilyInviteCodeCleanerMock creates a new instance of FamilyInviteCodeCleanerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFamilyInviteCodeCleanerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FamilyInviteCodeCleanerMock {
	mock := &FamilyInviteCodeCleanerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FamilyInviteCodeCleanerMock is an autogenerated mock type for the FamilyInviteCodeCleaner type
type FamilyInviteCodeCleanerMock struct {
	mock.Mock
}

type FamilyInviteCodeCleanerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FamilyInviteCodeCleanerMock) EXPECT() *FamilyInviteCodeCleanerMock_Expecter {
	return &FamilyInviteCodeCleanerMock_Expecter{mock: &_m.Mock}
}

// ClearInviteCodes provides a mock function for the type FamilyInviteCodeCleanerMock
func (_mock *FamilyInviteCodeCleanerMock) ClearInviteCodes(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearInviteCodes")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FamilyInviteCodeCleanerMock_ClearInviteCodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearInviteCodes'
type FamilyInviteCodeCleanerMock_ClearInviteCodes_Call struct {
	*mock.Call
}

// ClearInviteCodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *FamilyInviteCodeCleanerMock_Expecter) ClearInviteCodes(ctx interface{}) *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call {
	return &FamilyInviteCodeCleanerMock_ClearInviteCodes_Call{Call: _e.mock.On("ClearInviteCodes", ctx)}
}

func (_c *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call) Run(run func(ctx context.Context)) *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call) Return(err error) *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call) RunAndReturn(run func(ctx context.Context) error) *FamilyInviteCodeCleanerMock_ClearInviteCodes_Call {
	_c.Call.Return(run)
	return _c
}
